# Generated by Django 5.2.4 on 2025-07-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_alter_facture_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='montant',
            new_name='montant_ht',
        ),
        migrations.AddField(
            model_name='facture',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=4),
        ),
    ]
